baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'YIMBYpedia'

[params]
  customCSS = ["css/tailwind.css"]

[taxonomies]
  jurisdiction = "jurisdictions"
  jurisdictionType = "jurisdiction_types"
  status = "statuses"
  tag = "tags"