baseURL = 'https://yimbypedia.org/'
languageCode = 'en-us'
title = 'YIMBYpedia'

[taxonomies]
  jurisdiction = "jurisdictions"
  jurisdictionType = "jurisdiction_types"
  sponsor = "sponsors"
  status = "statuses"
  tag = "tags"